### ISSUE TITLE
Method override error

### ISSUE THREAD

**Issue by toddams** [azchohfi/SectionedRecyclerview.Droid#1]
While building a project I get this error:

```
Error    error: getItemCount() in AvailabilityAdapter cannot override getItemCount() in SectionedRecyclerViewAdapter
public int getItemCount ()
overridden method is final  ProjectName.Droid   D:\\path\to\project\AvailabilityAdapter.java    32  
```

Maybe you know what is the source of this issue?

**Comment by azchohfi** [comment]
I have absolutely no idea.
This repository is a **Xamarin.Android** binding project.

The original Java project is at:
https://github.com/afollestad/sectioned-recyclerview/

I believe you reported the issue at the wrong repository.
